import { createHash } from "node:crypto";
import { readdir, readFile, stat } from "node:fs/promises";
import path from "node:path";

import { EVENT_SCHEMA_VERSION } from "../core/contract.js";

const DAY_MS = 86_400_000;
const TARGET_TOOLS = new Set(["TaskCreate", "TaskUpdate", "AskUserQuestion"]);
const SAFE_TASK_STATUSES = new Set(["pending", "in_progress", "completed", "deleted"]);

function isRecord(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function stableAlias(prefix, value, length = 20) {
  const digest = createHash("sha256").update(String(value)).digest("hex").slice(0, length);
  return `${prefix}-${digest}`;
}

function normalizeTimestamp(value) {
  if (typeof value !== "string" && typeof value !== "number") return null;
  const milliseconds = typeof value === "number" && value < 10_000_000_000 ? value * 1_000 : Date.parse(value);
  if (!Number.isFinite(milliseconds)) return null;
  return new Date(milliseconds).toISOString();
}

function normalizeTaskId(value) {
  if (typeof value === "string" && value.trim() !== "") return value.trim();
  if (Number.isSafeInteger(value) && value >= 0) return String(value);
  return null;
}

// TaskCreate's tool result is generated by Claude Code itself. Extract only the
// numeric identifier from its fixed prefix; never retain or return the trailing
// task subject.
function taskIdFromCreateResult(block) {
  if (block?.type !== "tool_result" || typeof block.content !== "string") return null;
  const match = /^Task\s*#?\s*(\d+)\s+created\s+successfully\b/i.exec(block.content);
  return match?.[1] ?? null;
}

function safeBlocks(content, { parseMachineTaskResult = true } = {}) {
  if (!Array.isArray(content)) return [];
  const blocks = [];

  for (let index = 0; index < content.length; index += 1) {
    const block = content[index];
    if (!isRecord(block)) continue;

    if (block.type === "tool_use" && TARGET_TOOLS.has(block.name)) {
      const input = isRecord(block.input) ? block.input : {};
      blocks.push({
        blockIndex: index,
        type: "tool_use",
        name: block.name,
        toolUseId: typeof block.id === "string" ? block.id : null,
        taskId: block.name === "TaskUpdate" ? normalizeTaskId(input.taskId) : null,
        status:
          block.name === "TaskUpdate" && SAFE_TASK_STATUSES.has(input.status)
            ? input.status
            : null,
        dependencyCount:
          block.name === "TaskUpdate"
            ? (Array.isArray(input.addBlockedBy) ? input.addBlockedBy.length : 0) +
              (Array.isArray(input.addBlocks) ? input.addBlocks.length : 0)
            : 0,
      });
      continue;
    }

    if (block.type === "tool_result" && typeof block.tool_use_id === "string") {
      blocks.push({
        blockIndex: index,
        type: "tool_result",
        toolUseId: block.tool_use_id,
        // Stable turn segmentation is deliberately structure-only. The
        // legacy session view may retain its narrow machine-result mapping for
        // backward compatibility, but turn mode never inspects result prose.
        createdTaskId: parseMachineTaskResult ? taskIdFromCreateResult(block) : null,
        isError: block.is_error === true,
      });
    }
  }

  return blocks;
}

function contentShape(content) {
  if (typeof content === "string") return { kind: "string", blockTypes: [] };
  if (!Array.isArray(content)) return { kind: "other", blockTypes: [] };
  return {
    kind: "blocks",
    blockTypes: content.map((block) => (isRecord(block) && typeof block.type === "string" ? block.type : null)),
  };
}

function safeRecord(raw, index, options) {
  if (!isRecord(raw)) return null;
  const message = isRecord(raw.message) ? raw.message : {};
  const shape = contentShape(message.content);
  return {
    index,
    // Assistant message IDs can legitimately repeat across separate JSONL
    // envelopes. The append-only line ordinal prevents event-id collisions;
    // native IDs are only transient hash inputs and never leave the adapter.
    recordId: `${
      typeof raw.uuid === "string"
        ? raw.uuid
        : typeof message.id === "string"
          ? message.id
          : "record"
    }|line-${index + 1}`,
    uuid: typeof raw.uuid === "string" && raw.uuid !== "" ? raw.uuid : null,
    parentUuid: typeof raw.parentUuid === "string" && raw.parentUuid !== "" ? raw.parentUuid : null,
    sessionId: typeof raw.sessionId === "string" && raw.sessionId !== "" ? raw.sessionId : null,
    timestamp: normalizeTimestamp(raw.timestamp),
    type: typeof raw.type === "string" ? raw.type : null,
    subtype: typeof raw.subtype === "string" ? raw.subtype : null,
    role: typeof message.role === "string" ? message.role : null,
    stopReason: typeof message.stop_reason === "string" ? message.stop_reason : null,
    isSidechain: raw.isSidechain === true,
    isMeta: raw.isMeta === true,
    contentKind: shape.kind,
    contentBlockTypes: shape.blockTypes,
    blocks: safeBlocks(message.content, options),
  };
}

function isConversationRecord(record, sessionKind) {
  const expectedSidechain = sessionKind === "sidechain";
  return (
    record.isSidechain === expectedSidechain &&
    !record.isMeta &&
    (record.type === "user" || record.type === "assistant") &&
    (record.role === "user" || record.role === "assistant")
  );
}

function isHumanTurnBoundary(record) {
  if (record.type !== "user" || record.role !== "user" || record.isSidechain || record.isMeta) return false;
  if (record.contentKind === "string") return true;
  if (record.contentKind !== "blocks" || record.contentBlockTypes.length === 0) return false;
  return record.contentBlockTypes.some((type) => type !== "tool_result");
}

/**
 * Split a primary transcript by ancestry, not line adjacency. A turn begins at
 * a non-sidechain user envelope whose content is not exclusively tool_result
 * blocks. Every later envelope must reach that UUID through parentUuid links
 * to belong to the turn. Missing UUID/ancestry fails closed.
 */
function segmentHumanTurns(records, sessionKind) {
  if (sessionKind !== "primary") {
    return {
      turns: [],
      orphanConversationRecordCount: 0,
      unsegmentableHumanBoundaryCount: 0,
      duplicateRecordUuidCount: 0,
    };
  }

  const conversation = records.filter((record) => isConversationRecord(record, "primary"));
  // Non-conversation envelopes (for example system hook summaries) can sit in
  // the parent chain. They are safe graph links but never become emitted turn
  // records or boundaries.
  const byUuid = new Map();
  const duplicateUuids = new Set();
  for (const record of records) {
    if (record.uuid === null) continue;
    if (byUuid.has(record.uuid)) duplicateUuids.add(record.uuid);
    else byUuid.set(record.uuid, record);
  }

  const boundaryRecords = conversation.filter(isHumanTurnBoundary);
  const stableBoundaries = boundaryRecords.filter((record) => record.uuid !== null);
  const boundaryIds = new Set(stableBoundaries.map((record) => record.uuid));
  const grouped = new Map(stableBoundaries.map((record) => [record.uuid, { anchor: record, records: [] }]));
  let orphanConversationRecordCount = 0;
  const orphanIndices = [];

  for (const record of conversation) {
    let cursor = record;
    const visited = new Set();
    let anchorId = null;
    while (cursor !== null && cursor.uuid !== null && !visited.has(cursor.uuid)) {
      if (boundaryIds.has(cursor.uuid)) {
        anchorId = cursor.uuid;
        break;
      }
      visited.add(cursor.uuid);
      cursor = cursor.parentUuid === null ? null : byUuid.get(cursor.parentUuid) ?? null;
    }
    if (anchorId === null) {
      orphanConversationRecordCount += 1;
      orphanIndices.push(record.index);
      continue;
    }
    grouped.get(anchorId).records.push(record);
  }

  const turns = [...grouped.values()]
    .map((turn) => ({ ...turn, records: turn.records.sort((a, b) => a.index - b.index) }))
    .sort((a, b) => a.anchor.index - b.anchor.index);
  for (let index = 0; index < turns.length; index += 1) {
    const nextBoundaryIndex = turns[index + 1]?.anchor.index ?? Number.POSITIVE_INFINITY;
    turns[index].hasAmbiguousAncestry = orphanIndices.some(
      (orphanIndex) => orphanIndex > turns[index].anchor.index && orphanIndex < nextBoundaryIndex,
    );
    turns[index].hasDuplicateUuid = turns[index].records.some((record) => duplicateUuids.has(record.uuid));
    // Contract the full UUID graph onto conversation records. Bookkeeping
    // envelopes may sit between two messages, so direct child counts would
    // mislabel them as branches.
    const recordIds = new Set(turns[index].records.map((record) => record.uuid));
    const conversationParents = new Set();
    for (const record of turns[index].records) {
      let cursor = record.parentUuid === null ? null : byUuid.get(record.parentUuid) ?? null;
      const visited = new Set();
      while (cursor !== null && cursor.uuid !== null && !visited.has(cursor.uuid)) {
        if (recordIds.has(cursor.uuid)) {
          conversationParents.add(cursor.uuid);
          break;
        }
        visited.add(cursor.uuid);
        cursor = cursor.parentUuid === null ? null : byUuid.get(cursor.parentUuid) ?? null;
      }
    }
    turns[index].conversationLeaves = turns[index].records.filter(
      (record) => !conversationParents.has(record.uuid),
    );
    turns[index].endTurnSignalCount = turns[index].records.filter(
      (record) =>
        record.type === "assistant" &&
        record.role === "assistant" &&
        record.stopReason === "end_turn",
    ).length;
    const terminalLeaves = turns[index].conversationLeaves.filter(
      (record) =>
        record.type === "assistant" &&
        record.role === "assistant" &&
        record.stopReason === "end_turn",
    );
    turns[index].hasMixedTerminalLeaves =
      terminalLeaves.length > 0 && terminalLeaves.length < turns[index].conversationLeaves.length;
  }
  return {
    turns,
    orphanConversationRecordCount,
    unsegmentableHumanBoundaryCount: boundaryRecords.length - stableBoundaries.length,
    duplicateRecordUuidCount: duplicateUuids.size,
  };
}

function isUnambiguousHumanTurn(turn) {
  return (
    !turn.hasAmbiguousAncestry &&
    !turn.hasDuplicateUuid &&
    turn.endTurnSignalCount <= 1 &&
    !turn.hasMixedTerminalLeaves
  );
}

function isSafelyTerminalHumanTurn(turn) {
  const { anchor, records } = turn;
  const last = records.at(-1);
  return (
    isUnambiguousHumanTurn(turn) &&
    anchor.timestamp !== null &&
    last?.uuid !== null &&
    last?.timestamp !== null &&
    Date.parse(last.timestamp) >= Date.parse(anchor.timestamp) &&
    turn.conversationLeaves.length === 1 &&
    turn.conversationLeaves[0]?.uuid === last?.uuid &&
    last?.type === "assistant" &&
    last?.role === "assistant" &&
    last?.stopReason === "end_turn"
  );
}

function stepSnapshot(stepMap) {
  return [...stepMap.values()].map((step) => ({
    id: step.id,
    label: step.label,
    class: "other",
    status: step.status,
  }));
}

function eventFactory({ sourceKey, runId, nativeSessionId, sessionKind }) {
  const confidence = sessionKind === "primary" ? 0.96 : 0.9;
  return ({ kind, timestamp, reference, data = {} }) => ({
    schema_version: EVENT_SCHEMA_VERSION,
    event_id: stableAlias("claude-event", `${sourceKey}|${reference}|${kind}`, 24),
    run_id: runId,
    provider: "claude",
    native_session_id: nativeSessionId,
    occurred_at: timestamp,
    observed_at: timestamp,
    kind,
    source: {
      adapter: "claude-code-jsonl",
      mode: "local_readonly_metadata",
      confidence,
    },
    data,
  });
}

function canonicalScopeEvents(
  eligibleRecords,
  { sourceKey, runId, nativeSessionId, sessionKind, stableReferences, allowTerminal = true },
) {
  const makeEvent = eventFactory({ sourceKey, runId, nativeSessionId, sessionKind });
  const timestampedRecords = eligibleRecords.filter((record) => record.timestamp !== null);
  if (timestampedRecords.length === 0) return [];

  const createdTaskIds = new Map();
  for (const record of eligibleRecords) {
    for (const block of record.blocks) {
      if (block.type === "tool_result" && block.createdTaskId !== null) {
        createdTaskIds.set(block.toolUseId, block.createdTaskId);
      }
    }
  }

  const first = timestampedRecords[0];
  const events = [
    makeEvent({
      kind: "run_started",
      timestamp: first.timestamp,
      reference: `${stableReferences ? first.uuid : first.recordId}|run-started`,
      data: { model_family: "claude" },
    }),
  ];
  const steps = new Map();
  const askToolIds = new Set();
  let planRevision = 0;

  function ensureStep(nativeTaskId) {
    const safeTaskId = stableAlias("claude-step", `${sourceKey}|${nativeTaskId}`, 16);
    if (!steps.has(nativeTaskId)) {
      steps.set(nativeTaskId, {
        id: safeTaskId,
        label: `步骤 ${steps.size + 1}`,
        status: "pending",
      });
    }
    return steps.get(nativeTaskId);
  }

  for (const record of eligibleRecords) {
    if (record.timestamp === null) continue;

    for (const block of record.blocks) {
      const recordReference = stableReferences ? record.uuid : record.recordId;
      if (recordReference === null) continue;
      const reference = `${recordReference}|${block.blockIndex}`;
      if (block.type === "tool_use" && block.name === "TaskCreate") {
        const nativeTaskId =
          createdTaskIds.get(block.toolUseId) ?? stableAlias("unmapped-task", block.toolUseId ?? reference, 12);
        ensureStep(nativeTaskId);
        planRevision += 1;
        events.push(
          makeEvent({
            kind: planRevision === 1 ? "plan_declared" : "plan_revised",
            timestamp: record.timestamp,
            reference: `${reference}|plan-${planRevision}`,
            data: { revision: planRevision, steps: stepSnapshot(steps) },
          }),
        );
        continue;
      }

      if (block.type === "tool_use" && block.name === "TaskUpdate" && block.taskId !== null) {
        const wasKnown = steps.has(block.taskId);
        const step = ensureStep(block.taskId);
        if (!wasKnown) {
          planRevision += 1;
          events.push(
            makeEvent({
              kind: planRevision === 1 ? "plan_declared" : "plan_revised",
              timestamp: record.timestamp,
              reference: `${reference}|discovered-plan-${planRevision}`,
              data: { revision: planRevision, steps: stepSnapshot(steps) },
            }),
          );
        }

        if (block.status === "in_progress" && step.status !== "in_progress") {
          const kind = step.status === "completed" ? "retry_started" : "step_started";
          step.status = "in_progress";
          events.push(
            makeEvent({
              kind,
              timestamp: record.timestamp,
              reference: `${reference}|${kind}`,
              data: { step_id: step.id },
            }),
          );
        } else if (block.status === "completed" && step.status !== "completed") {
          step.status = "completed";
          events.push(
            makeEvent({
              kind: "step_completed",
              timestamp: record.timestamp,
              reference: `${reference}|step-completed`,
              data: { step_id: step.id },
            }),
          );
        } else if (
          (block.status === "pending" || block.status === "deleted") &&
          step.status !== (block.status === "deleted" ? "cancelled" : "pending")
        ) {
          step.status = block.status === "deleted" ? "cancelled" : "pending";
          planRevision += 1;
          events.push(
            makeEvent({
              kind: "plan_revised",
              timestamp: record.timestamp,
              reference: `${reference}|plan-${planRevision}`,
              data: { revision: planRevision, steps: stepSnapshot(steps) },
            }),
          );
        }
        continue;
      }

      if (block.type === "tool_use" && block.name === "AskUserQuestion") {
        if (block.toolUseId !== null) askToolIds.add(block.toolUseId);
        events.push(
          makeEvent({
            kind: "needs_input",
            timestamp: record.timestamp,
            reference: `${reference}|needs-input`,
          }),
        );
        continue;
      }

      if (block.type === "tool_result" && askToolIds.has(block.toolUseId)) {
        askToolIds.delete(block.toolUseId);
        events.push(
          makeEvent({
            kind: "resumed",
            timestamp: record.timestamp,
            reference: `${reference}|resumed`,
          }),
        );
      }
    }
  }

  const lastConversation = eligibleRecords.at(-1);
  if (
    allowTerminal &&
    lastConversation?.timestamp !== null &&
    lastConversation?.type === "assistant" &&
    lastConversation?.role === "assistant" &&
    lastConversation?.stopReason === "end_turn"
  ) {
    events.push(
      makeEvent({
        kind: "run_succeeded",
        timestamp: lastConversation.timestamp,
        reference: `${stableReferences ? lastConversation.uuid : lastConversation.recordId}|run-succeeded`,
      }),
    );
  }

  return events
    .map((event, index) => ({ event, index }))
    .sort((a, b) => Date.parse(a.event.occurred_at) - Date.parse(b.event.occurred_at) || a.index - b.index)
    .map(({ event }) => event);
}

function canonicalEvents(records, { file, sessionId, sessionKind }) {
  const sourceKey = `${sessionId}|${path.basename(file)}`;
  return canonicalScopeEvents(records.filter((record) => isConversationRecord(record, sessionKind)), {
    sourceKey,
    runId: stableAlias("claude-run", sourceKey),
    nativeSessionId: stableAlias("claude-session", sessionId),
    sessionKind,
    stableReferences: false,
  });
}

function canonicalTurnEvents(segmentation, { sessionId }) {
  const nativeSessionId = stableAlias("claude-session", sessionId);
  return segmentation.turns
    .flatMap((turn) => {
      const { anchor, records } = turn;
      if (anchor.uuid === null || anchor.timestamp === null || !isUnambiguousHumanTurn(turn)) return [];
      const sourceKey = `${sessionId}|human-turn|${anchor.uuid}`;
      return canonicalScopeEvents(records, {
        sourceKey,
        runId: stableAlias("claude-run", sourceKey),
        nativeSessionId,
        sessionKind: "primary",
        stableReferences: true,
        // Coverage may record the currently terminal-shaped envelope, but a
        // later append can add another envelope for the same assistant
        // response. Without a checkpoint or retraction, turn mode must never
        // emit an irreversible terminal event.
        allowTerminal: false,
      });
    })
    .map((event, index) => ({ event, index }))
    .sort((a, b) =>
      Date.parse(a.event.occurred_at) - Date.parse(b.event.occurred_at) ||
      a.event.run_id.localeCompare(b.event.run_id) ||
      a.index - b.index,
    )
    .map(({ event }) => event);
}

/**
 * Parse one Claude Code JSONL transcript into privacy-safe metadata, coverage,
 * and (optionally) canonical lifecycle/plan events. Transcript prose, prompts,
 * code, commands, paths inside messages, and native identifiers are never
 * returned. Step names are deliberately ordinal labels.
 */
export async function scanClaudeSession(file, { includeEvents = true, segmentation = "session" } = {}) {
  if (typeof file !== "string" || file.trim() === "") {
    throw new TypeError("file must be a non-empty path string");
  }
  if (segmentation !== "session" && segmentation !== "turns") {
    throw new TypeError('segmentation must be either "session" or "turns"');
  }

  const [contents, fileStat] = await Promise.all([readFile(file, "utf8"), stat(file)]);
  const records = [];
  let totalLines = 0;
  let parsedLines = 0;
  let malformedLines = 0;

  for (const line of contents.split(/\r?\n/)) {
    if (line.trim() === "") continue;
    totalLines += 1;
    try {
      const record = safeRecord(JSON.parse(line), totalLines - 1, {
        parseMachineTaskResult: segmentation === "session",
      });
      if (record !== null) records.push(record);
      parsedLines += 1;
    } catch {
      malformedLines += 1;
    }
  }

  const explicitSessionId = records.find((record) => record.sessionId !== null)?.sessionId ?? null;
  const rawSessionId = explicitSessionId ?? path.basename(file, ".jsonl");
  const primaryRecordCount = records.filter(
    (record) => !record.isSidechain && (record.type === "user" || record.type === "assistant"),
  ).length;
  const sidechainRecordCount = records.filter(
    (record) => record.isSidechain && (record.type === "user" || record.type === "assistant"),
  ).length;
  const metaConversationRecordCount = records.filter(
    (record) =>
      record.isMeta &&
      (record.type === "user" || record.type === "assistant") &&
      (record.role === "user" || record.role === "assistant"),
  ).length;
  const sessionKind = primaryRecordCount > 0 ? "primary" : sidechainRecordCount > 0 ? "sidechain" : "metadata_only";
  const eventRecords = records.filter((record) => isConversationRecord(record, sessionKind));
  const turnSegmentation = segmentHumanTurns(records, sessionKind);
  const terminalHumanTurnCount = turnSegmentation.turns.filter(isSafelyTerminalHumanTurn).length;
  const plannedHumanTurnCount = turnSegmentation.turns.filter((turn) =>
    turn.records.some((record) => record.blocks.some(
      (block) => block.type === "tool_use" && (block.name === "TaskCreate" || block.name === "TaskUpdate"),
    )),
  ).length;
  const ambiguousHumanTurnCount = turnSegmentation.turns.filter(
    (turn) => !isUnambiguousHumanTurn(turn),
  ).length;
  const timestamps = records.map((record) => record.timestamp).filter((value) => value !== null);
  const toolUses = eventRecords.flatMap((record) => record.blocks).filter((block) => block.type === "tool_use");
  const taskCreateCount = toolUses.filter((block) => block.name === "TaskCreate").length;
  const taskUpdateCount = toolUses.filter((block) => block.name === "TaskUpdate").length;
  const needsInputCount = toolUses.filter((block) => block.name === "AskUserQuestion").length;
  const mappedTaskCreateCount = records
    .flatMap((record) => record.blocks)
    .filter((block) => block.type === "tool_result" && block.createdTaskId !== null).length;
  const dependencyDeclarationCount = toolUses.reduce(
    (sum, block) => sum + (block.name === "TaskUpdate" ? block.dependencyCount : 0),
    0,
  );
  const lastConversation = eventRecords.at(-1);
  const terminalDetected =
    lastConversation?.type === "assistant" &&
    lastConversation?.role === "assistant" &&
    lastConversation?.stopReason === "end_turn";
  const sourceKey = `${rawSessionId}|${path.basename(file)}`;
  const nativeSessionId = stableAlias("claude-session", rawSessionId);
  const metadata = {
    provider: "claude",
    sourceId: stableAlias("claude-source", sourceKey),
    nativeSessionId,
    runId: stableAlias("claude-run", sourceKey),
    sessionKind,
    modifiedAt: fileStat.mtime.toISOString(),
    byteSize: fileStat.size,
    firstTimestamp: timestamps[0] ?? null,
    lastTimestamp: timestamps.at(-1) ?? null,
    rawSessionIdPresent: records.some((record) => record.sessionId !== null),
  };
  const coverage = {
    totalLines,
    parsedLines,
    malformedLines,
    timestampedRecords: timestamps.length,
    primaryRecordCount,
    sidechainRecordCount,
    metaConversationRecordCount,
    taskCreateCount,
    mappedTaskCreateCount,
    unmappedTaskCreateCount: Math.max(0, taskCreateCount - mappedTaskCreateCount),
    taskUpdateCount,
    dependencyDeclarationCount,
    hasNativePlan: taskCreateCount + taskUpdateCount > 0,
    needsInputCount,
    terminalDetected,
    humanTurnCount: turnSegmentation.turns.length,
    terminalHumanTurnCount,
    nonterminalHumanTurnCount: turnSegmentation.turns.length - terminalHumanTurnCount,
    plannedHumanTurnCount,
    ambiguousHumanTurnCount,
    multipleTerminalHumanTurnCount: turnSegmentation.turns.filter(
      (turn) => turn.endTurnSignalCount > 1,
    ).length,
    mixedTerminalLeafHumanTurnCount: turnSegmentation.turns.filter(
      (turn) => turn.hasMixedTerminalLeaves,
    ).length,
    orphanConversationRecordCount: turnSegmentation.orphanConversationRecordCount,
    unsegmentableHumanBoundaryCount: turnSegmentation.unsegmentableHumanBoundaryCount,
    duplicateRecordUuidCount: turnSegmentation.duplicateRecordUuidCount,
    turnSegmentation: "structural-ancestry-v1",
    turnIdentityEligible: sessionKind === "primary" && explicitSessionId !== null,
  };

  const result = { metadata, coverage };
  if (includeEvents) {
    result.events =
      segmentation === "turns"
        ? explicitSessionId === null
          ? []
          : canonicalTurnEvents(turnSegmentation, { sessionId: explicitSessionId })
        : canonicalEvents(records, {
            file,
            sessionId: rawSessionId,
            sessionKind,
          });
  }
  return result;
}

/** Experimental structural human-turn view; terminal events stay coverage-only. */
export function scanClaudeTurns(file, { includeEvents = true } = {}) {
  return scanClaudeSession(file, { includeEvents, segmentation: "turns" });
}

async function jsonlFiles(root) {
  const rootStat = await stat(root);
  if (rootStat.isFile()) return root.endsWith(".jsonl") ? [path.resolve(root)] : [];
  if (!rootStat.isDirectory()) return [];

  const files = [];
  async function walk(directory) {
    const entries = await readdir(directory, { withFileTypes: true });
    await Promise.all(
      entries.map(async (entry) => {
        const candidate = path.join(directory, entry.name);
        if (entry.isDirectory()) await walk(candidate);
        else if (entry.isFile() && entry.name.endsWith(".jsonl")) files.push(candidate);
      }),
    );
  }
  await walk(root);
  return files;
}

/** Discover recently modified Claude JSONL sources and report explicit coverage denominators. */
export async function discoverClaudeSessions({ root, since = Date.now() - 30 * DAY_MS } = {}) {
  if (typeof root !== "string" || root.trim() === "") {
    throw new TypeError("root must be a non-empty path string");
  }
  const sinceMs = since instanceof Date ? since.getTime() : typeof since === "number" ? since : Date.parse(since);
  if (!Number.isFinite(sinceMs)) throw new TypeError("since must be a Date, timestamp, or date string");

  const candidates = await jsonlFiles(path.resolve(root));
  const recent = [];
  for (const file of candidates) {
    const fileStat = await stat(file);
    if (fileStat.mtimeMs >= sinceMs) recent.push({ file, mtimeMs: fileStat.mtimeMs });
  }
  recent.sort((a, b) => b.mtimeMs - a.mtimeMs || a.file.localeCompare(b.file));

  // `file` is an ephemeral local capability for callers that choose to scan a
  // discovered source. It is intentionally kept outside scan metadata so it
  // cannot accidentally enter reports or forecast persistence.
  const sessions = [];
  for (const { file } of recent) {
    sessions.push({ file, ...(await scanClaudeSession(file, { includeEvents: false })) });
  }
  const primary = sessions.filter((session) => session.metadata.sessionKind === "primary");
  const sidechains = sessions.filter((session) => session.metadata.sessionKind === "sidechain");
  const metadataOnly = sessions.filter((session) => session.metadata.sessionKind === "metadata_only");
  const planned = sessions.filter((session) => session.coverage.hasNativePlan);
  const primaryPlanned = primary.filter((session) => session.coverage.hasNativePlan);
  const uniqueSessionCount = new Set(sessions.map((session) => session.metadata.nativeSessionId)).size;
  const ratio = (numerator, denominator) => (denominator === 0 ? null : numerator / denominator);

  return {
    provider: "claude",
    since: new Date(sinceMs).toISOString(),
    sessions,
    coverage: {
      discoveredFiles: sessions.length,
      uniqueSessionCount,
      primarySessionFiles: primary.length,
      sidechainSessionFiles: sidechains.length,
      metadataOnlyFiles: metadataOnly.length,
      nativePlanFiles: planned.length,
      primaryNativePlanFiles: primaryPlanned.length,
      allFilePlanCoverage: ratio(planned.length, sessions.length),
      primaryPlanCoverage: ratio(primaryPlanned.length, primary.length),
      terminalFiles: sessions.filter((session) => session.coverage.terminalDetected).length,
      needsInputFiles: sessions.filter((session) => session.coverage.needsInputCount > 0).length,
      humanTurns: sessions.reduce((sum, session) => sum + session.coverage.humanTurnCount, 0),
      terminalHumanTurns: sessions.reduce(
        (sum, session) => sum + session.coverage.terminalHumanTurnCount,
        0,
      ),
      nonterminalHumanTurns: sessions.reduce(
        (sum, session) => sum + session.coverage.nonterminalHumanTurnCount,
        0,
      ),
      plannedHumanTurns: sessions.reduce(
        (sum, session) => sum + session.coverage.plannedHumanTurnCount,
        0,
      ),
      humanTurnPlanCoverage: ratio(
        sessions.reduce((sum, session) => sum + session.coverage.plannedHumanTurnCount, 0),
        sessions.reduce((sum, session) => sum + session.coverage.humanTurnCount, 0),
      ),
      ambiguousHumanTurns: sessions.reduce(
        (sum, session) => sum + session.coverage.ambiguousHumanTurnCount,
        0,
      ),
      multipleTerminalHumanTurns: sessions.reduce(
        (sum, session) => sum + session.coverage.multipleTerminalHumanTurnCount,
        0,
      ),
      mixedTerminalLeafHumanTurns: sessions.reduce(
        (sum, session) => sum + session.coverage.mixedTerminalLeafHumanTurnCount,
        0,
      ),
      metaConversationRecords: sessions.reduce(
        (sum, session) => sum + session.coverage.metaConversationRecordCount,
        0,
      ),
      orphanConversationRecords: sessions.reduce(
        (sum, session) => sum + session.coverage.orphanConversationRecordCount,
        0,
      ),
      unsegmentableHumanBoundaries: sessions.reduce(
        (sum, session) => sum + session.coverage.unsegmentableHumanBoundaryCount,
        0,
      ),
      turnIdentityEligibleFiles: sessions.filter((session) => session.coverage.turnIdentityEligible).length,
      duplicateRecordUuids: sessions.reduce(
        (sum, session) => sum + session.coverage.duplicateRecordUuidCount,
        0,
      ),
      malformedLines: sessions.reduce((sum, session) => sum + session.coverage.malformedLines, 0),
      taskCreateEvents: sessions.reduce((sum, session) => sum + session.coverage.taskCreateCount, 0),
      taskUpdateEvents: sessions.reduce((sum, session) => sum + session.coverage.taskUpdateCount, 0),
      dependencyDeclarations: sessions.reduce(
        (sum, session) => sum + session.coverage.dependencyDeclarationCount,
        0,
      ),
    },
  };
}
